# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'httparty'

group :test, :development do
  gem 'pry'
  gem 'rspec'
  gem 'rubocop', '~> 0.74.0', require: false
  gem 'rubocop-performance'
  gem 'rubocop-salemove'
  gem 'vcr'
  gem 'webmock'
end
